from __future__ import annotations

import json
import sqlite3
import struct
from pathlib import Path
from threading import RLock
from typing import Any, Callable, TypeVar

from core.application_data import get_app_data_service
from faces.models import Face, FaceCluster, FaceEmbedding, Person, utc_now

T = TypeVar("T")


def _vector_to_blob(vector: tuple[float, ...]) -> bytes:
    return struct.pack(f"<{len(vector)}f", *vector)


def _blob_to_vector(blob: bytes, dimension: int) -> tuple[float, ...]:
    if len(blob) != dimension * 4:
        raise ValueError("Stored face embedding does not match its dimension.")
    return tuple(struct.unpack(f"<{dimension}f", blob))


class SQLiteFaceRepository:
    """Portable SQLite persistence for all MODEL-004A repositories.

    Stable domain IDs are supplied by the models rather than generated by the
    database. Upserts and model-keyed embedding rows support incremental scans,
    corrected assignments, and future reprocessing without destructive resets.
    """

    SCHEMA_VERSION = 1

    def __init__(self, db_path: str | Path | None = None):
        if db_path is None:
            db_path = get_app_data_service().root / "data" / "faces" / "face_intelligence.sqlite3"
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = RLock()
        self._initialize()

    def _connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self.db_path)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys=ON")
        return connection

    def _initialize(self) -> None:
        with self._lock, self._connect() as connection:
            connection.execute("PRAGMA journal_mode=WAL")
            connection.executescript(
                """
                CREATE TABLE IF NOT EXISTS face_schema (
                    version INTEGER NOT NULL
                );
                CREATE TABLE IF NOT EXISTS persons (
                    id TEXT PRIMARY KEY, payload TEXT NOT NULL,
                    name TEXT NOT NULL, updated_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS clusters (
                    id TEXT PRIMARY KEY, payload TEXT NOT NULL,
                    person_id TEXT, updated_at TEXT NOT NULL,
                    FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE SET NULL
                );
                CREATE TABLE IF NOT EXISTS faces (
                    id TEXT PRIMARY KEY, image_id TEXT NOT NULL,
                    source_fingerprint TEXT NOT NULL, payload TEXT NOT NULL,
                    person_id TEXT, cluster_id TEXT, updated_at TEXT NOT NULL,
                    FOREIGN KEY(person_id) REFERENCES persons(id) ON DELETE SET NULL,
                    FOREIGN KEY(cluster_id) REFERENCES clusters(id) ON DELETE SET NULL
                );
                CREATE TABLE IF NOT EXISTS face_embeddings (
                    face_id TEXT NOT NULL, model_key TEXT NOT NULL,
                    provider_id TEXT NOT NULL, model_id TEXT NOT NULL,
                    model_revision TEXT NOT NULL, dimension INTEGER NOT NULL,
                    vector_blob BLOB, source_fingerprint TEXT NOT NULL,
                    generated_at TEXT NOT NULL, status TEXT NOT NULL, error TEXT NOT NULL,
                    PRIMARY KEY(face_id, model_key),
                    FOREIGN KEY(face_id) REFERENCES faces(id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS idx_faces_image ON faces(image_id);
                CREATE INDEX IF NOT EXISTS idx_faces_person ON faces(person_id);
                CREATE INDEX IF NOT EXISTS idx_faces_cluster ON faces(cluster_id);
                CREATE INDEX IF NOT EXISTS idx_embeddings_model ON face_embeddings(model_key, status);
                CREATE TABLE IF NOT EXISTS face_assignment_audit (
                    id INTEGER PRIMARY KEY AUTOINCREMENT, face_id TEXT NOT NULL,
                    person_id TEXT, action TEXT NOT NULL, created_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS rejected_face_suggestions (
                    face_id TEXT NOT NULL, person_id TEXT NOT NULL, created_at TEXT NOT NULL,
                    PRIMARY KEY(face_id, person_id)
                );
                CREATE INDEX IF NOT EXISTS idx_face_audit_face ON face_assignment_audit(face_id);
                CREATE TABLE IF NOT EXISTS face_processing_results (
                    image_id TEXT PRIMARY KEY, source_fingerprint TEXT NOT NULL,
                    detector_key TEXT NOT NULL, processing_version TEXT NOT NULL,
                    status TEXT NOT NULL, face_count INTEGER NOT NULL DEFAULT 0,
                    failure_code TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_face_processing_status ON face_processing_results(status,detector_key);
                """
            )
            row = connection.execute("SELECT version FROM face_schema LIMIT 1").fetchone()
            if row is None:
                connection.execute("INSERT INTO face_schema(version) VALUES (?)", (self.SCHEMA_VERSION,))
            elif int(row[0]) != self.SCHEMA_VERSION:
                raise RuntimeError(f"Unsupported face database schema: {row[0]}")

    def save_face(self, face: Face) -> Face:
        face.updated_at = utc_now()
        payload = json.dumps(face.to_dict(), ensure_ascii=False, sort_keys=True)
        with self._lock, self._connect() as connection:
            connection.execute(
                """INSERT INTO faces(id,image_id,source_fingerprint,payload,person_id,cluster_id,updated_at)
                   VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET
                   image_id=excluded.image_id, source_fingerprint=excluded.source_fingerprint,
                   payload=excluded.payload, person_id=excluded.person_id,
                   cluster_id=excluded.cluster_id, updated_at=excluded.updated_at""",
                (face.id, face.image_id, face.source_fingerprint, payload, face.person_id, face.cluster_id, face.updated_at),
            )
        return face

    def get_face(self, face_id: str) -> Face | None:
        faces = self._faces("SELECT payload,person_id,cluster_id FROM faces WHERE id=?", (face_id,))
        return faces[0] if faces else None

    def faces_for_image(self, image_id: str) -> list[Face]:
        return self._faces("SELECT payload,person_id,cluster_id FROM faces WHERE image_id=? ORDER BY updated_at,id", (image_id,))

    def faces_for_person(self, person_id: str) -> list[Face]:
        return self._faces("SELECT payload,person_id,cluster_id FROM faces WHERE person_id=? ORDER BY image_id,id", (person_id,))

    def faces_for_cluster(self, cluster_id: str) -> list[Face]:
        return self._faces("SELECT payload,person_id,cluster_id FROM faces WHERE cluster_id=? ORDER BY image_id,id", (cluster_id,))

    def unassigned_faces(self) -> list[Face]:
        return self._faces("SELECT payload,person_id,cluster_id FROM faces WHERE person_id IS NULL ORDER BY image_id,id")

    def delete_faces_for_image(self, image_id: str) -> int:
        with self._lock, self._connect() as connection:
            cursor = connection.execute("DELETE FROM faces WHERE image_id=?", (image_id,))
            return cursor.rowcount

    def list_faces(self) -> list[Face]:
        return self._faces("SELECT payload,person_id,cluster_id FROM faces ORDER BY image_id,id")

    def get_processing_result(self, image_id: str) -> dict[str, Any] | None:
        with self._lock, self._connect() as connection:
            row = connection.execute("SELECT * FROM face_processing_results WHERE image_id=?", (image_id,)).fetchone()
        return dict(row) if row else None

    def save_processing_result(self, image_id: str, fingerprint: str, detector_key: str,
                               status: str, face_count: int = 0, failure_code: str = "",
                               processing_version: str = "face-worker-v1") -> None:
        with self._lock, self._connect() as connection:
            connection.execute(
                """INSERT INTO face_processing_results VALUES(?,?,?,?,?,?,?,?)
                   ON CONFLICT(image_id) DO UPDATE SET source_fingerprint=excluded.source_fingerprint,
                   detector_key=excluded.detector_key,processing_version=excluded.processing_version,
                   status=excluded.status,face_count=excluded.face_count,
                   failure_code=excluded.failure_code,updated_at=excluded.updated_at""",
                (image_id, fingerprint, detector_key, processing_version, status,
                 int(face_count), failure_code, utc_now()))

    def assign_cluster(self, cluster_id: str, person_id: str) -> int:
        """Confirm all non-false-positive members in one transaction and audit them."""
        now = utc_now()
        with self._lock, self._connect() as connection:
            rows = connection.execute("SELECT id,payload FROM faces WHERE cluster_id=?", (cluster_id,)).fetchall()
            count = 0
            for row in rows:
                payload = json.loads(row["payload"])
                if payload.get("false_positive"): continue
                payload.update(person_id=person_id, assignment_source="manual_cluster",
                               assignment_confidence=1.0, assignment_confirmed=True,
                               updated_at=now, revision=int(payload.get("revision", 1)) + 1)
                connection.execute("UPDATE faces SET person_id=?,payload=?,updated_at=? WHERE id=?",
                                   (person_id, json.dumps(payload, sort_keys=True), now, row["id"]))
                connection.execute("INSERT INTO face_assignment_audit(face_id,person_id,action,created_at) VALUES(?,?,?,?)",
                                   (row["id"], person_id, "manual_confirm", now))
                count += 1
            connection.execute("UPDATE clusters SET person_id=?,updated_at=? WHERE id=?", (person_id, now, cluster_id))
            return count

    def reject_suggestion(self, face_id: str, person_id: str) -> None:
        with self._lock, self._connect() as connection:
            connection.execute("INSERT OR REPLACE INTO rejected_face_suggestions VALUES(?,?,?)", (face_id, person_id, utc_now()))

    def clear_face_analysis(self) -> None:
        """Delete biometric-like analysis while preserving original photos and categories."""
        with self._lock, self._connect() as connection:
            connection.execute("DELETE FROM rejected_face_suggestions")
            connection.execute("DELETE FROM face_assignment_audit")
            connection.execute("DELETE FROM face_embeddings")
            connection.execute("DELETE FROM faces")
            connection.execute("DELETE FROM clusters")
            connection.execute("DELETE FROM face_processing_results")

    def save_person(self, person: Person) -> Person:
        person.updated_at = utc_now()
        payload = json.dumps(person.to_dict(), ensure_ascii=False, sort_keys=True)
        with self._lock, self._connect() as connection:
            connection.execute(
                """INSERT INTO persons(id,payload,name,updated_at) VALUES(?,?,?,?)
                   ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,name=excluded.name,updated_at=excluded.updated_at""",
                (person.id, payload, person.name, person.updated_at),
            )
        return person

    def get_person(self, person_id: str) -> Person | None:
        return self._one("SELECT payload FROM persons WHERE id=?", (person_id,), Person.from_dict)

    def list_persons(self, name_query: str = "") -> list[Person]:
        query = "SELECT payload FROM persons"
        args: tuple[Any, ...] = ()
        if name_query:
            query += " WHERE name LIKE ? ESCAPE '\\'"
            escaped = name_query.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
            args = (f"%{escaped}%",)
        return self._items(query + " ORDER BY name COLLATE NOCASE,id", args, Person.from_dict)

    def delete_person(self, person_id: str) -> bool:
        return self._delete("DELETE FROM persons WHERE id=?", person_id)

    def save_cluster(self, cluster: FaceCluster) -> FaceCluster:
        cluster.updated_at = utc_now()
        payload = json.dumps(cluster.to_dict(), ensure_ascii=False, sort_keys=True)
        with self._lock, self._connect() as connection:
            connection.execute(
                """INSERT INTO clusters(id,payload,person_id,updated_at) VALUES(?,?,?,?)
                   ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,person_id=excluded.person_id,updated_at=excluded.updated_at""",
                (cluster.id, payload, cluster.person_id, cluster.updated_at),
            )
        return cluster

    def get_cluster(self, cluster_id: str) -> FaceCluster | None:
        items = self._clusters("SELECT payload,person_id FROM clusters WHERE id=?", (cluster_id,))
        return items[0] if items else None

    def list_clusters(self) -> list[FaceCluster]:
        return self._clusters("SELECT payload,person_id FROM clusters ORDER BY updated_at,id", ())

    def delete_cluster(self, cluster_id: str) -> bool:
        return self._delete("DELETE FROM clusters WHERE id=?", cluster_id)

    def save_embedding(self, embedding: FaceEmbedding) -> FaceEmbedding:
        with self._lock, self._connect() as connection:
            connection.execute(
                """INSERT INTO face_embeddings(face_id,model_key,provider_id,model_id,model_revision,
                   dimension,vector_blob,source_fingerprint,generated_at,status,error) VALUES(?,?,?,?,?,?,?,?,?,?,?)
                   ON CONFLICT(face_id,model_key) DO UPDATE SET vector_blob=excluded.vector_blob,
                   source_fingerprint=excluded.source_fingerprint,generated_at=excluded.generated_at,
                   status=excluded.status,error=excluded.error""",
                (embedding.face_id, embedding.model_key, embedding.provider_id, embedding.model_id,
                 embedding.model_revision, embedding.dimension, _vector_to_blob(embedding.vector),
                 embedding.source_fingerprint, embedding.generated_at, embedding.status, embedding.error),
            )
        return embedding

    def get_embedding(self, face_id: str, model_key: str) -> FaceEmbedding | None:
        rows = self._embedding_rows("SELECT * FROM face_embeddings WHERE face_id=? AND model_key=?", (face_id, model_key))
        return rows[0] if rows else None

    def embeddings_for_model(self, model_key: str, only_current: bool = True) -> list[FaceEmbedding]:
        query = "SELECT e.* FROM face_embeddings e"
        if only_current:
            query += " JOIN faces f ON f.id=e.face_id AND f.source_fingerprint=e.source_fingerprint"
        query += " WHERE e.model_key=? AND e.status='ok' ORDER BY e.face_id"
        return self._embedding_rows(query, (model_key,))

    def invalidate_face_embeddings(self, face_id: str) -> int:
        return self._invalidate("face_id=?", (face_id,))

    def invalidate_model_embeddings(self, model_key: str) -> int:
        return self._invalidate("model_key=?", (model_key,))

    def _invalidate(self, condition: str, args: tuple[Any, ...]) -> int:
        with self._lock, self._connect() as connection:
            cursor = connection.execute(f"UPDATE face_embeddings SET status='stale' WHERE {condition} AND status='ok'", args)
            return cursor.rowcount

    def _faces(self, query: str, args: tuple[Any, ...] = ()) -> list[Face]:
        with self._lock, self._connect() as connection:
            rows = connection.execute(query, args).fetchall()
        faces: list[Face] = []
        for row in rows:
            payload = json.loads(row["payload"])
            payload["person_id"] = row["person_id"]
            payload["cluster_id"] = row["cluster_id"]
            faces.append(Face.from_dict(payload))
        return faces

    def _clusters(self, query: str, args: tuple[Any, ...]) -> list[FaceCluster]:
        with self._lock, self._connect() as connection:
            rows = connection.execute(query, args).fetchall()
        clusters: list[FaceCluster] = []
        for row in rows:
            payload = json.loads(row["payload"])
            payload["person_id"] = row["person_id"]
            clusters.append(FaceCluster.from_dict(payload))
        return clusters

    def _one(self, query: str, args: tuple[Any, ...], factory: Callable[[dict[str, Any]], T]) -> T | None:
        items = self._items(query, args, factory)
        return items[0] if items else None

    def _items(self, query: str, args: tuple[Any, ...], factory: Callable[[dict[str, Any]], T]) -> list[T]:
        with self._lock, self._connect() as connection:
            rows = connection.execute(query, args).fetchall()
        return [factory(json.loads(row[0])) for row in rows]

    def _embedding_rows(self, query: str, args: tuple[Any, ...]) -> list[FaceEmbedding]:
        with self._lock, self._connect() as connection:
            rows = connection.execute(query, args).fetchall()
        return [FaceEmbedding(
            face_id=row["face_id"], provider_id=row["provider_id"], model_id=row["model_id"],
            model_revision=row["model_revision"], dimension=row["dimension"],
            vector=_blob_to_vector(row["vector_blob"] or b"", row["dimension"]),
            source_fingerprint=row["source_fingerprint"], generated_at=row["generated_at"],
            status=row["status"], error=row["error"],
        ) for row in rows]

    def _delete(self, query: str, identifier: str) -> bool:
        with self._lock, self._connect() as connection:
            return connection.execute(query, (identifier,)).rowcount > 0
