from __future__ import annotations

from typing import Protocol, runtime_checkable

from faces.models import Face, FaceCluster, FaceEmbedding, Person


@runtime_checkable
class FaceRepository(Protocol):
    def save_face(self, face: Face) -> Face: ...
    def get_face(self, face_id: str) -> Face | None: ...
    def faces_for_image(self, image_id: str) -> list[Face]: ...
    def faces_for_person(self, person_id: str) -> list[Face]: ...
    def faces_for_cluster(self, cluster_id: str) -> list[Face]: ...
    def unassigned_faces(self) -> list[Face]: ...
    def delete_faces_for_image(self, image_id: str) -> int: ...


@runtime_checkable
class PersonRepository(Protocol):
    def save_person(self, person: Person) -> Person: ...
    def get_person(self, person_id: str) -> Person | None: ...
    def list_persons(self, name_query: str = "") -> list[Person]: ...
    def delete_person(self, person_id: str) -> bool: ...


@runtime_checkable
class ClusterRepository(Protocol):
    def save_cluster(self, cluster: FaceCluster) -> FaceCluster: ...
    def get_cluster(self, cluster_id: str) -> FaceCluster | None: ...
    def list_clusters(self) -> list[FaceCluster]: ...
    def delete_cluster(self, cluster_id: str) -> bool: ...


@runtime_checkable
class FaceEmbeddingRepository(Protocol):
    def save_embedding(self, embedding: FaceEmbedding) -> FaceEmbedding: ...
    def get_embedding(self, face_id: str, model_key: str) -> FaceEmbedding | None: ...
    def embeddings_for_model(self, model_key: str, only_current: bool = True) -> list[FaceEmbedding]: ...
    def invalidate_face_embeddings(self, face_id: str) -> int: ...
    def invalidate_model_embeddings(self, model_key: str) -> int: ...
